package com.uitopic.restock.platform.communications.interfaces.rest.resources;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;

/**
 * Record representing a request resource for registering a push notification subscription in the REST API.
 * This resource is used to transfer the necessary data from the client to the server when a user wants to register a new push subscription.
 */
@Schema(description = "Request resource for registering a push notification subscription")
public record RegisterPushSubscriptionResource(
        @NotBlank
        @Schema(description = "User identifier")
        String userId,

        @NotBlank
        @Schema(description = "Provider token generated by the client notification provider")
        String providerToken,

        @NotBlank
        @Schema(description = "Client platform: WEB, ANDROID, IOS")
        String clientPlatform,

        @NotBlank
        @Schema(description = "Notification provider: FCM, ONE_SIGNAL")
        String provider
) {
}
