package com.uitopic.restock.platform.iam.infrastructure.persistence.mongodb.assemblers;

import com.uitopic.restock.platform.iam.domain.model.entities.Role;
import com.uitopic.restock.platform.iam.infrastructure.persistence.mongodb.entities.RolePersistenceEntity;

/**
 * RolePersistenceAssembler is a utility class responsible for converting between Role domain entities and RolePersistenceEntity objects used for MongoDB persistence. It provides static methods to facilitate the transformation of data between the domain model and the persistence layer, ensuring that the application can seamlessly interact with the database while maintaining a clear separation of concerns.
 */
public final class RolePersistenceAssembler {

    private RolePersistenceAssembler() {
        // Private constructor to prevent instantiation
    }

    /**
     * Converts a RolePersistenceEntity from MongoDB into a Role domain entity. This method takes the data stored in the persistence entity, including the ID and type, and creates a corresponding Role domain object that can be used within the application. If the input entity is null, this method will return null.
     *
     * @param entity The RolePersistenceEntity retrieved from MongoDB that contains the data to be converted into a Role domain entity. This may include the ID and type of the role as stored in the database.
     * @return A Role domain entity that represents the data from the given RolePersistenceEntity. If the input entity is null, this method will return null, indicating that there is no role to convert.
     */
    public static Role toDomainFromPersistence(RolePersistenceEntity entity) {
        if (entity == null) return null;
        return new Role(entity.getId(), entity.getType());
    }

    /**
     * Converts a Role domain entity to a RolePersistenceEntity for storage in MongoDB. If the Role has an ID, it is included in the persistence entity; otherwise, it will be generated by MongoDB upon insertion.
     *
     * @param role The Role domain entity to be converted to a persistence entity. This may contain an ID if the role already exists, or it may be null for new roles that have not yet been persisted.
     * @return A RolePersistenceEntity that represents the given Role domain entity, ready for storage in MongoDB. If the input role is null, this method will return null.
     */
    public static RolePersistenceEntity toPersistenceFromDomain(Role role) {
        if (role == null) return null;
        var entity = new RolePersistenceEntity();
        if (role.getId() != null) {
            entity.setId(role.getId());
        }
        entity.setType(role.getType());
        return entity;
    }
}
