# Server Configuration
server.port=${PORT:8080}

# Spring Application Name
spring.application.name=Restock API

# MongoDB Configuration
spring.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017}
spring.mongodb.database=${MONGODB_DATABASE:restock_db}
spring.data.mongodb.auto-index-creation=true

# Application Information for Documentation
documentation.application.description=@project.description@
# suppress inspection "SpringBootApplicationProperties"
documentation.application.version=@project.version@

# JWT Configuration Properties
# suppress inspection "SpringBootApplicationProperties"
authorization.jwt.secret=${JWT_SECRET:WriteHereYourSecretStringForTokenSigningCredentials}
# suppress inspection "SpringBootApplicationProperties"
authorization.jwt.expiration.days=${JWT_EXPIRATION_DAYS:7}

# Springdoc OpenAPI Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# Cloudinary Configuration Properties
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dplnowmib}
cloudinary.api-key=${CLOUDINARY_API_KEY:878197382771939}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:ggv-8EF1qsNbIiyWQeAKKs2GB38}

# Redis Configuration
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.timeout=2000ms