# Server Configuration
server.port=${PORT:8080}

# Spring Application Name
spring.application.name=Restock API

# MongoDB Configuration
spring.mongodb.uri=mongodb://localhost:27017
spring.mongodb.database=restock_db
spring.data.mongodb.auto-index-creation=true

# Application Information for Documentation

# Elements take their values from maven pom.xml build-related information

# Custom Properties for Documentation
# suppress inspection "SpringBootApplicationProperties"
documentation.application.description=@project.description@
# suppress inspection "SpringBootApplicationProperties"
documentation.application.version=@project.version@
# Security autoconfiguration is handled by WebSecurityConfiguration

# JWT Configuration Properties

# Custom Properties for JWT
# suppress inspection "SpringBootApplicationProperties"
authorization.jwt.secret = WriteHereYourSecretStringForTokenSigningCredentials
# suppress inspection "SpringBootApplicationProperties"
authorization.jwt.expiration.days = 7

# Springdoc OpenAPI Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# Cloudinary Configuration Properties
cloudinary.cloud-name=dplnowmib
cloudinary.api-key=878197382771939
cloudinary.api-secret=ggv-8EF1qsNbIiyWQeAKKs2GB38