# Server Configuration
server.port=${PORT:8080}

# Spring Application Name
spring.application.name=Restock API

# MongoDB Configuration
spring.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017}
spring.mongodb.database=${MONGODB_DATABASE:restock_db}
spring.data.mongodb.auto-index-creation=true

# Application Information for Documentation
documentation.application.description=@project.description@
documentation.application.version=@project.version@

# JWT Configuration Properties
authorization.jwt.secret=${JWT_SECRET}
authorization.jwt.expiration.days=7

# Springdoc OpenAPI Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# Cloudinary Configuration Properties
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# Redis Configuration
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.timeout=2000ms

# Firebase Configuration Properties
integrations.fcm.enabled=${INTEGRATIONS_FCM_ENABLED:true}
firebase.project.id=${FIREBASE_PROJECT_ID}
firebase.credentials.base64=${FIREBASE_CREDENTIALS_BASE64}

# Resend API Configuration
resend.api.key=${RESEND_API_KEY}

# Edge Service Configuration
edge.service.url=http://127.0.0.1:5003/api/v1
edge.service.iam.url=/auth/sign-up
edge.service.device-thresholds.url=/devices/{device_id}/thresholds
edge.service.device-display-mode.url=/devices/{device_id}/display-mode

# Stripe Configuration
stripe.secret.key=${STRIPE_SECRET_KEY}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}
stripe.success.url=${STRIPE_SUCCESS_URL}
stripe.cancel.url=${STRIPE_CANCEL_URL}

# File Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
