package com.uitopic.restock.platform.iam.infrastructure.persistence.mongodb.entities;

import com.uitopic.restock.platform.iam.domain.model.valueobjects.RoleType;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.FieldType;
import org.springframework.data.mongodb.core.mapping.MongoId;

/**
 * RolePersistenceEntity is a MongoDB document that represents a role within the IAM (Identity and Access Management) system. It contains an identifier and a type that defines the specific permissions and access levels associated with this role.
 */
@Data
@NoArgsConstructor
@Document(collection = "roles")
public class RolePersistenceEntity {

    /**
     * Unique identifier for the Role entity, typically generated by the database.
     */
    @MongoId(FieldType.OBJECT_ID)
    private String id;

    /**
     * The type of the role, represented as a RoleType value object, which defines the specific permissions and access levels associated with this role.
     */
    private RoleType type;
}
