package com.uitopic.restock.platform.tracking.domain.model.entities;

import com.uitopic.restock.platform.shared.domain.model.valueobjects.AccountId;
import com.uitopic.restock.platform.shared.domain.model.valueobjects.BatchId;
import com.uitopic.restock.platform.shared.domain.model.valueobjects.BranchId;
import com.uitopic.restock.platform.shared.domain.model.valueobjects.DeviceId;
import com.uitopic.restock.platform.tracking.domain.exceptions.DiscrepancyResolutionException;
import com.uitopic.restock.platform.tracking.domain.model.aggregates.StockComparisonTask;
import com.uitopic.restock.platform.tracking.domain.model.valueobjects.*;
import lombok.*;

import java.time.Instant;

/**
 * Entity representing a discrepancy in inventory tracking. It captures the details of the discrepancy, including its unique identifier, risk level, quantity difference, and associated device ID. This entity is used to track and manage inventory discrepancies within the system.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@With
public class Discrepancy {

    /**
     * The unique identifier for the discrepancy, generated by the system. This is used to track and reference specific discrepancies in the inventory tracking process.
     */
    private String id;

    /**
     * The stock comparison task that originated this discrepancy.
     */
    private String stockComparisonTaskId;

    /**
     * The account related to this discrepancy.
     */
    private AccountId accountId;

    /**
     * The branch related to this discrepancy.
     */
    private BranchId branchId;

    /**
     * The batch related to this discrepancy.
     */
    private BatchId batchId;

    /**
     * The custom supply identifier related to this discrepancy.
     */
    private String customSupplyId;

    /**
     * The custom supply name related to this discrepancy.
     */
    private String customSupplyName;

    /**
     * The physical stock detected by the device.
     */
    private StockRecord physicalStock;

    /**
     * The stock registered in the system.
     */
    private StockRecord systemStock;

    /**
     * The stock used in the comparison, which may include justified withdrawn stock if applicable..
     */
    private Double justifiedWithdrawnStockUsed;

    /**
     * The total physical stock used in the comparison, which includes both the physical stock obtained from the count and any justified withdrawn stock.
     */
    private Double totalPhysicalStock;

    /**
     * The risk level of the discrepancy, provided by the request. This indicates the severity of the inventory discrepancy.
     */
    private DiscrepancyAlertLevel riskLevel;

    /**
     * The quantity difference between the physical and system inventory levels, provided by the comparison task.
     */
    private Double quantityDifference;

    /**
     * The status of the discrepancy, which can be "RESOLVED" or "UNRESOLVED". This is used to track the resolution process of the discrepancy.
     */
    private DiscrepancyStatus status;

    /**
     * The device ID associated with the discrepancy, provided by the request.
     */
    private DeviceId deviceId;

    /**
     * The timestamp when the discrepancy was created.
     */
    private Instant createdAt;

    /**
     * The timestamp when the discrepancy was resolved.
     */
    private Instant resolvedAt;

    /**
     * Creates a discrepancy from a mismatched stock comparison task.
     *
     * @param stockComparisonTask the completed stock comparison task with MISMATCH result
     * @param riskLevel the risk level assigned to the discrepancy
     */
    public Discrepancy(
            StockComparisonTask stockComparisonTask,
            DiscrepancyAlertLevel riskLevel
    ) {
        if (stockComparisonTask == null) {
            throw new DiscrepancyResolutionException("Stock comparison task cannot be null");
        }

        if (stockComparisonTask.getId() == null || stockComparisonTask.getId().isBlank()) {
            throw new DiscrepancyResolutionException("Stock comparison task ID cannot be null or blank");
        }

        if (stockComparisonTask.getResult() != ComparisonResult.MISMATCH) {
            throw new DiscrepancyResolutionException("Only mismatched stock comparisons can create discrepancies");
        }

        if (riskLevel == null) {
            throw new DiscrepancyResolutionException("Risk level cannot be null");
        }

        this.stockComparisonTaskId = stockComparisonTask.getId();
        this.accountId = stockComparisonTask.getAccountId();
        this.branchId = stockComparisonTask.getBranchId();
        this.batchId = stockComparisonTask.getBatchId();
        this.customSupplyId = stockComparisonTask.getCustomSupplyId();
        this.customSupplyName = stockComparisonTask.getCustomSupplyName();

        this.justifiedWithdrawnStockUsed = stockComparisonTask.getJustifiedWithdrawnStockUsed();
        this.totalPhysicalStock = stockComparisonTask.getTotalPhysicalStock();
        
        this.physicalStock = stockComparisonTask.getPhysicalStock();
        this.systemStock = stockComparisonTask.getSystemStock();
        this.quantityDifference = stockComparisonTask.getDifference();

        this.riskLevel = riskLevel;
        this.status = DiscrepancyStatus.UNRESOLVED;
        this.deviceId = stockComparisonTask.getDeviceId();
        this.createdAt = Instant.now();
    }

    /**
     * Resolves the discrepancy.
     */
    public void resolve() {
        if (this.status == DiscrepancyStatus.RESOLVED) {
            throw new DiscrepancyResolutionException("Discrepancy is already resolved");
        }

        this.status = DiscrepancyStatus.RESOLVED;
        this.resolvedAt = Instant.now();
    }
}
