package com.uitopic.restock.platform.resources.infrastructure.persistence.mongodb.entities;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.FieldType;
import org.springframework.data.mongodb.core.mapping.MongoId;

/**
 * Represents the persistence entity for a supply template in the MongoDB database.
 * This class is used to store and retrieve supply template information, including its name, description, category, and whether it is perishable. The unique identifier for each supply template is generated by Mongo
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "supplies")
public class SupplyPersistenceEntity {

    /**
     * Unique identifier for the supply template, generated by the database.
     */
    @MongoId(value = FieldType.STRING)
    private String id;

    /**
     * Display name of the supply template.
     */
    private String name;

    /**
     * Description of the supply and its main characteristics.
     */
    private String description;

    /**
     * Category or type assigned to this supply.
     */
    private String category;

    /**
     * Indicates whether this supply requires expiration date tracking.
     */
    private Boolean isPerishable;
}
