package com.uitopic.restock.platform.resources.interfaces.rest.resources;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.PositiveOrZero;

/**
 * Request resource for creating a batch.
 *
 * The entry date is generated by the backend.
 * The unit of measurement is taken from the related custom supply.
 */
@Schema(description = "Request resource for creating a batch")
public record CreateBatchResource(
        @NotBlank
        @Schema(description = "Batch code")
        String code,

        @NotNull
        @PositiveOrZero
        @Schema(description = "Current stock quantity")
        Double currentStock,

        @NotBlank
        @Schema(description = "Custom supply ID")
        String customSupplyId,

        @NotBlank
        @Schema(description = "Branch ID")
        String branchId,

        @Schema(description = "Expiration date in ISO format, e.g. 2026-12-31")
        String expirationDate
) {
}