package com.uitopic.restock.platform.tracking.infrastructure.persistence.mongodb.entities;

import com.uitopic.restock.platform.shared.domain.model.valueobjects.AccountId;
import com.uitopic.restock.platform.shared.domain.model.valueobjects.BatchId;
import com.uitopic.restock.platform.shared.domain.model.valueobjects.BranchId;
import com.uitopic.restock.platform.shared.domain.model.valueobjects.DeviceId;
import com.uitopic.restock.platform.tracking.domain.model.valueobjects.DiscrepancyAlertLevel;
import com.uitopic.restock.platform.tracking.domain.model.valueobjects.DiscrepancyStatus;
import com.uitopic.restock.platform.tracking.domain.model.valueobjects.StockRecord;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.FieldType;
import org.springframework.data.mongodb.core.mapping.MongoId;

/**
 * Persistence entity representing a discrepancy in inventory tracking, designed for storage in a MongoDB collection.
 * This entity captures the details of the discrepancy, including its unique identifier, risk level, quantity difference, status, and associated device ID. The @Document annotation specifies that this class is mapped to the "discrepancies" collection in MongoDB, and the @MongoId annotation indicates that the "id" field is the primary key for the collection.
 */
@Data
@NoArgsConstructor
@Document(collection = "discrepancies")
public class DiscrepancyPersistenceEntity {

    /**
     * The unique identifier for the discrepancy, generated by the system. This is used to track and reference specific discrepancies in the inventory tracking process. The @MongoId annotation indicates that this field is the primary key for the MongoDB collection, and the FieldType.OBJECT_ID specifies that it should be stored as an ObjectId in MongoDB.
     */
    @MongoId(FieldType.OBJECT_ID)
    private String id;
    private String stockComparisonTaskId;
    private AccountId accountId;
    private BranchId branchId;
    private BatchId batchId;
    private String customSupplyId;
    private String customSupplyName;
    private StockRecord physicalStock;
    private StockRecord systemStock;
    private Double justifiedWithdrawnStockUsed;
    private Double totalPhysicalStock;

    /**
     * The risk level of the discrepancy, provided by the request. This indicates the severity of the inventory discrepancy and can be used to prioritize resolution efforts. The risk level is determined based on the quantity difference and other factors related to the inventory tracking process.
     */
    private DiscrepancyAlertLevel riskLevel;

    /**
     * The quantity difference between the physical and system inventory levels, provided by the comparison task. This field captures the magnitude of the discrepancy in inventory levels, which can be used to assess the severity of the issue and prioritize resolution efforts.
     */
    private Double quantityDifference;

    /**
     * The status of the discrepancy, which can be "RESOLVED" or "UNRESOLVED". This is used to track the resolution process of the discrepancy. The status is initialized to "UNRESOLVED" when a new discrepancy is created and can be updated to "RESOLVED" once the issue has been addressed.
     */
    private DiscrepancyStatus status;

    /**
     * The device ID associated with the discrepancy, provided by the request. This is used to track and reference specific discrepancies in the inventory tracking process.
     */
    private DeviceId deviceId;
    private java.time.Instant createdAt;
    private java.time.Instant resolvedAt;
}
