package com.uitopic.restock.platform.tracking.infrastructure.persistence.mongodb.entities;

import com.uitopic.restock.platform.shared.domain.model.valueobjects.DeviceId;
import com.uitopic.restock.platform.tracking.domain.model.valueobjects.HumidityRecord;
import com.uitopic.restock.platform.tracking.domain.model.valueobjects.StockRecord;
import com.uitopic.restock.platform.tracking.domain.model.valueobjects.TemperatureRecord;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.FieldType;
import org.springframework.data.mongodb.core.mapping.MongoId;

import java.time.Instant;

/**
 * Persistence entity representing a telemetry reading from a device, containing information about stock levels, temperature, humidity, and the timestamp of the reading. This entity is used to store telemetry readings in a MongoDB collection for tracking inventory discrepancies and monitoring environmental conditions in real-time.
 */
@Data
@NoArgsConstructor
@Document(collection = "telemetry_readings")
public class TelemetryReadingPersistenceEntity {

    /**
     * Unique identifier for the telemetry reading, generated by the system. This field is annotated with @MongoId to indicate that it is the primary key for the MongoDB collection, and it uses the ObjectId type for efficient storage and retrieval.
     */
    @MongoId(FieldType.STRING)
    private String id;

    /**
     * The physical stock level recorded by the device at the time of the reading.
     */
    private StockRecord physicalStock;

    /**
     * The temperature recorded by the device at the time of the reading, in degrees Celsius.
     */
    private TemperatureRecord temperatureInCelsius;

    /**
     * The humidity percentage recorded by the device at the time of the reading, as a value between 0 and 100.
     */
    private HumidityRecord humidityPercentage;

    /**
     * The timestamp when the telemetry reading was recorded, in ISO 8601 format. This represents the exact time the reading was taken by the device.
     */
    private Instant timestamp = Instant.now();

    /**
     * The unique identifier of the device that provided the telemetry reading. This is used to associate the reading with a specific device for tracking inventory discrepancies.
     */
    private DeviceId deviceId;
}
