package com.uitopic.restock.platform.planning.domain.model.aggregates;

import com.uitopic.restock.platform.planning.domain.model.entities.Ingredient;
import com.uitopic.restock.platform.planning.domain.model.valueobjects.ProductType;
import com.uitopic.restock.platform.shared.domain.model.aggregates.AbstractDomainAggregateRoot;
import com.uitopic.restock.platform.shared.domain.model.valueobjects.AccountId;
import jakarta.validation.constraints.NotBlank;
import lombok.*;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Optional;

/**
 * Aggregate root for the {@code planning} bounded context.
 *
 * <p>A {@code Product} models either a <em>recipe</em> (a prepared dish assembled from measured
 * ingredients) or a <em>kit</em> (a bundle of components), and is identified within a tenant
 * account via {@link AccountId}.  All mutations to the embedded {@code ingredients} list must
 * pass through the public methods defined here, preserving aggregate consistency.</p>
 *
 * <p>The document is stored in the {@code products} MongoDB collection.  The
 * {@code ingredients} sub-array is persisted as embedded documents — no separate collection.</p>
 */
@EqualsAndHashCode(callSuper = true)
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Product extends AbstractDomainAggregateRoot<Product> {

    /**
     * The unique identifier for this product, generated by MongoDB upon insertion.  Exposed as a string for ease of use in the application layer, but stored as an ObjectId in the database.
     */
    private String id;

    /**
     * The tenant account that owns this product.
     * Stored as {@link AccountId} and serialised by a registered MongoDB converter.
     */
    private AccountId accountId;

    /** Human-readable product name, unique per account. */
    @NotBlank
    private String name;

    /** Optional description providing additional context about the product. */
    @NotBlank
    private String description;

    /**
     * Stock-Keeping Unit identifier.
     * Should be unique per account; uniqueness is enforced at the application layer.
     */
    @NotBlank
    private String sku;

    /** Discriminates between {@code RECIPE} and {@code KIT} products. */
    private ProductType type;

    /** Optional URL pointing to a product image (e.g., a Cloudinary URL). */
    private String imageUrl;

    /** Selling price of the finished product. Currency semantics are defined externally. */
    private BigDecimal sellingPrice;

    /**
     * Embedded list of ingredients/components that make up this product.
     * Initialised eagerly to avoid {@code null} checks throughout the aggregate.
     */
    @Builder.Default
    private List<Ingredient> ingredients = new ArrayList<>();

    // -------------------------------------------------------------------------
    // Aggregate behaviour
    // -------------------------------------------------------------------------

    /**
     * Adds a new ingredient to this product.
     *
     * <p>This is the only sanctioned way to mutate the ingredients list.  Business rules enforced:
     * <ol>
     *   <li>A {@code customSupplyId} may appear at most once per product.</li>
     *   <li>The quantity must be positive.</li>
     *   <li>The {@code totalCost} is provided pre-calculated by the application service
     *       (which fetches the unit price from the {@code resources} bounded context via the
     *       {@link com.uitopic.restock.platform.planning.domain.services.CustomSupplyPricingPort}).</li>
     * </ol>
     *
     * @param ingredient the ingredient to add; must not be {@code null}
     * @throws IllegalArgumentException if {@code customSupplyId} is already present
     *                                  or if quantity is not positive
     */
    public void addIngredient(Ingredient ingredient) {
        if (ingredient.getQuantity() == null || ingredient.getQuantity() <= 0) {
            throw new IllegalArgumentException("Ingredient quantity must be a positive number.");
        }
        boolean alreadyPresent = this.ingredients.stream()
                .anyMatch(i -> i.getCustomSupplyId().equals(ingredient.getCustomSupplyId()));
        if (alreadyPresent) {
            throw new IllegalArgumentException(
                    "Ingredient with customSupplyId '" + ingredient.getCustomSupplyId()
                            + "' is already part of this product. Use update instead.");
        }
        this.ingredients.add(ingredient);
    }

    /**
     * Removes an ingredient from this product by its {@code customSupplyId}.
     *
     * @param customSupplyId the FK to the custom supply to remove
     * @throws IllegalArgumentException if no ingredient with that supply ID exists
     */
    public void removeIngredient(String customSupplyId) {
        boolean removed = this.ingredients.removeIf(
                i -> i.getCustomSupplyId().equals(customSupplyId));
        if (!removed) {
            throw new IllegalArgumentException(
                    "No ingredient with customSupplyId '" + customSupplyId + "' found in this product.");
        }
    }

    /**
     * Returns an unmodifiable view of the ingredients list to prevent external mutation.
     *
     * @return immutable list of ingredients
     */
    public List<Ingredient> getIngredients() {
        return Collections.unmodifiableList(ingredients);
    }

    /**
     * Finds an ingredient by its customSupplyId.
     *
     * @param customSupplyId the FK to search for
     * @return an {@link Optional} containing the ingredient if found
     */
    public Optional<Ingredient> findIngredientBySupplyId(String customSupplyId) {
        return this.ingredients.stream()
                .filter(i -> i.getCustomSupplyId().equals(customSupplyId))
                .findFirst();
    }

    /**
     * Updates the mutable product fields.
     *
     * @param name          new product name (ignored if {@code null})
     * @param description   new description (ignored if {@code null})
     * @param sku           new SKU (ignored if {@code null})
     * @param imageUrl      new image URL (ignored if {@code null})
     * @param sellingPrice  new selling price (ignored if {@code null})
     */
    public void update(String name, String description, String sku,
                       String imageUrl, BigDecimal sellingPrice) {
        if (name != null && !name.isBlank())        this.name = name;
        if (description != null)                     this.description = description;
        if (sku != null && !sku.isBlank())           this.sku = sku;
        if (imageUrl != null)                        this.imageUrl = imageUrl;
        if (sellingPrice != null)                    this.sellingPrice = sellingPrice;
    }
}
