package com.uitopic.restock.platform.planning.infrastructure.persistence.mongodb.assemblers;

import com.uitopic.restock.platform.planning.domain.model.entities.Ingredient;
import com.uitopic.restock.platform.planning.infrastructure.persistence.mongodb.entities.IngredientPersistenceEntity;

/**
 * Utility class for converting between Ingredient domain models and their corresponding persistence entities.
 */
public final class IngredientPersistenceAssembler {

    // Private constructor to prevent instantiation of this utility class
    private IngredientPersistenceAssembler() {
        throw new UnsupportedOperationException("Utility class");
    }

    /**
     * Converts a persistence entity to a domain Ingredient. If the input entity is null, returns null.
     *
     * @param entity The persistence entity to convert. If null, returns null.
     * @return A new Ingredient domain model instance with fields copied from the persistence entity. If the input is null, returns null.
     */
    public static Ingredient toDomainFromPersistence(IngredientPersistenceEntity entity) {
        if (entity == null) return null;

        var ingredient = new Ingredient();
        ingredient.setId(entity.getId());
        ingredient.setProductId(entity.getProductId());
        ingredient.setCustomSupplyId(entity.getCustomSupplyId());
        ingredient.setQuantity(entity.getQuantity());
        ingredient.setTotalCost(entity.getTotalCost());

        return ingredient;
    }

    /**
     * Converts a domain Ingredient to a persistence entity. If the domain model has an ID, it will be set in the entity;
     *
     * @param ingredient The domain model ingredient to convert. If null, returns null.
     * @return A new IngredientPersistenceEntity with fields copied from the domain model. The ID is only set if it exists in the domain model; otherwise, it is left null for MongoDB to generate.
     */
    public static IngredientPersistenceEntity toPersistenceFromDomain(Ingredient ingredient) {
        if (ingredient == null) return null;

        var entity = new IngredientPersistenceEntity();

        // Only set the ID if it exists in the domain model. For new ingredients, the ID will be generated by MongoDB.
        if (ingredient.getId() != null) {
            entity.setId(ingredient.getId());
        }
        entity.setProductId(ingredient.getProductId());
        entity.setCustomSupplyId(ingredient.getCustomSupplyId());
        entity.setQuantity(ingredient.getQuantity());
        entity.setTotalCost(ingredient.getTotalCost());

        return entity;
    }
}
